spring.application.name=ui_lab_india
# 1. The Connection String
# format: jdbc:postgresql://[host]:[port]/[database_name]
spring.datasource.url=jdbc:postgresql://localhost:5432/ui_lab_db

# 2. Your Database Credentials
spring.datasource.username=postgres
spring.datasource.password=root

# 3. The "Translator" (Dialect)
# This tells Hibernate to use PostgreSQL-specific SQL syntax
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 4. Schema Strategy (The "ddl-auto" setting)
# 'update' means Spring will compare your Java code to the DB
# and create/fix tables automatically every time you start the app.
spring.jpa.hibernate.ddl-auto=update

# 5. Developer Logging
# This prints the SQL Hibernate writes for you in the console.
# It's the best way to learn how JPA works.
spring.jpa.show-sql=true